name: WhereMyLife签到
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '15 23 * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - run: pip install requests
      - run: pip install bs4
      - run: python resource/daily_resetBook.py
           


      
